// <auto-generated />
using System;
using MediaTracker.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaTracker.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924195747_AddMediaItemUpdatedAt")]
    partial class AddMediaItemUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MediaTracker.Server.Models.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FranchiseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FranchiseOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("MediaItems");

                    b.HasDiscriminator<string>("MediaType").HasValue("MediaItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaTracker.Server.Models.TvSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TvShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.ToTable("TvSeasons");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.Book", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Models.MediaItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.Manga", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Models.MediaItem");

                    b.Property<int>("CurrentChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Manga");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.Movie", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Models.MediaItem");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_IsAnime");

                    b.Property<string>("RomajiTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("Movie_RomajiTitle");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT")
                        .HasColumnName("Movie_Studio");

                    b.HasIndex("IsAnime");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.TvShow", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Models.MediaItem");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TvShow_IsAnime");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<string>("RomajiTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("TvShow_RomajiTitle");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT")
                        .HasColumnName("TvShow_Studio");

                    b.HasIndex("IsAnime");

                    b.HasDiscriminator().HasValue("TvShow");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.VideoGame", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Models.MediaItem");

                    b.Property<int?>("HoursPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.MediaItem", b =>
                {
                    b.HasOne("MediaTracker.Server.Models.Franchise", "Franchise")
                        .WithMany("Items")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.TvSeason", b =>
                {
                    b.HasOne("MediaTracker.Server.Models.TvShow", "TvShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.Franchise", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MediaTracker.Server.Models.TvShow", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
