// <auto-generated />
using System;
using MediaTracker.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaTracker.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003193029_AddRelatedMediaToMediaItem")]
    partial class AddRelatedMediaToMediaItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.MangaVolume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MangaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MangaId");

                    b.HasIndex("MangaId", "VolumeNumber");

                    b.ToTable("MangaVolumes");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.MediaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MediaId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExternalRating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ExternalRatingVotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalRatingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FranchiseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FranchiseOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedMediaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSynopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockedAchievements")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPlatform")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("MediaType");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("MediaType", "Status", "CreatedAt");

                    b.ToTable("MediaItems");

                    b.HasDiscriminator<string>("MediaType").HasValue("MediaItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.TvSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodesData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TvShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.HasIndex("TvShowId", "SeasonNumber");

                    b.ToTable("TvSeasons");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.Book", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Domain.Entities.MediaItem");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.Manga", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Domain.Entities.MediaItem");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .HasColumnName("Manga_Author");

                    b.Property<int>("CurrentChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentVolume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT")
                        .HasColumnName("Manga_Format");

                    b.Property<string>("RomajiTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("Manga_RomajiTitle");

                    b.Property<int?>("TotalChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalVolumes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Manga_TotalVolumes");

                    b.HasDiscriminator().HasValue("Manga");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.Movie", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Domain.Entities.MediaItem");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Movie_IsAnime");

                    b.Property<string>("RomajiTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("Movie_RomajiTitle");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT")
                        .HasColumnName("Movie_Studio");

                    b.HasIndex("IsAnime");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.TvShow", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Domain.Entities.MediaItem");

                    b.Property<int?>("EpisodeDurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TvShow_EpisodeDurationMinutes");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TvShow_IsAnime");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<string>("RomajiTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("TvShow_RomajiTitle");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT")
                        .HasColumnName("TvShow_Studio");

                    b.HasIndex("IsAnime");

                    b.HasDiscriminator().HasValue("TvShow");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.VideoGame", b =>
                {
                    b.HasBaseType("MediaTracker.Server.Domain.Entities.MediaItem");

                    b.Property<int?>("HoursPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.MangaVolume", b =>
                {
                    b.HasOne("MediaTracker.Server.Domain.Entities.Manga", "Manga")
                        .WithMany("Volumes")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.MediaEvent", b =>
                {
                    b.HasOne("MediaTracker.Server.Domain.Entities.MediaItem", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.MediaItem", b =>
                {
                    b.HasOne("MediaTracker.Server.Domain.Entities.Franchise", "Franchise")
                        .WithMany("Items")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.TvSeason", b =>
                {
                    b.HasOne("MediaTracker.Server.Domain.Entities.TvShow", "TvShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.Franchise", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.Manga", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("MediaTracker.Server.Domain.Entities.TvShow", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
